name: CD
on:
  push:
    branches:
      - "main"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to the Docker registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Make .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL_SECRET }}
          file_name: .env
          fail_on_empty: true
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/javierlgroba/task-list/frontend:latest
